{
 "title": "eBPF",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "program",
    "query": "label_values(devagent_ebpf_prog_run_time, id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total eBPF load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(devagent_ebpf_prog_run_time{id=~\"$program\"}[1m]))"
    }
   ]
  },
  {
   "title": "Average duration per run",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(devagent_ebpf_prog_run_time{id=~\"$program\"}[1m]) / rate(devagent_ebpf_prog_run_count{id=~\"$program\"}[1m]))",
     "legendFormat": "{{id}} {{name}} {{type}} {{tag}}"
    }
   ]
  },
  {
   "title": "Program runs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(devagent_ebpf_prog_run_count{id=~\"$program\"}[1m]))"
    }
   ]
  }
 ]
}