// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Map struct {
	ID         int     `json:"id"`
	Fd         *int    `json:"fd,omitempty"`
	Name       *string `json:"name,omitempty"`
	Type       *string `json:"type,omitempty"`
	Flags      *int    `json:"flags,omitempty"`
	IsPinned   *bool   `json:"isPinned,omitempty"`
	KeySize    *int    `json:"keySize,omitempty"`
	ValueSize  *int    `json:"valueSize,omitempty"`
	MaxEntries *int    `json:"maxEntries,omitempty"`
	Error      *string `json:"error,omitempty"`
}

type Program struct {
	ID       int      `json:"id"`
	Name     *string  `json:"name,omitempty"`
	Type     string   `json:"type"`
	Tag      *string  `json:"tag,omitempty"`
	RunTime  *float64 `json:"runTime,omitempty"`
	RunCount *int     `json:"runCount,omitempty"`
	BtfID    *int     `json:"btfId,omitempty"`
	Maps     []*Map   `json:"maps"`
	Error    *string  `json:"error,omitempty"`
}
