// Code generated by "stringer -output types_string.go -type=TaskFdType"; DO NOT EDIT.

package tasks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RawTracepoint-0]
	_ = x[Tracepoint-1]
	_ = x[Kprobe-2]
	_ = x[Kretprobe-3]
	_ = x[Uprobe-4]
	_ = x[Uretprobe-5]
}

const _TaskFdType_name = "RawTracepointTracepointKprobeKretprobeUprobeUretprobe"

var _TaskFdType_index = [...]uint8{0, 13, 23, 29, 38, 44, 53}

func (i TaskFdType) String() string {
	if i >= TaskFdType(len(_TaskFdType_index)-1) {
		return "TaskFdType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskFdType_name[_TaskFdType_index[i]:_TaskFdType_index[i+1]]
}
